/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedQuickcashRouteImport } from './routes/_authenticated/quickcash'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLeagueRouteImport } from './routes/_authenticated/league'
import { Route as AuthenticatedLeaderboardsRouteImport } from './routes/_authenticated/leaderboards'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedTournamentsIndexRouteImport } from './routes/_authenticated/tournaments.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedTournamentsNewRouteImport } from './routes/_authenticated/tournaments.new'
import { Route as AuthenticatedTournamentsIdRouteImport } from './routes/_authenticated/tournaments.$id'
import { Route as AuthenticatedPlayerUserIdRouteImport } from './routes/_authenticated/player.$userId'
import { Route as AuthenticatedOnboardingProfileRouteImport } from './routes/_authenticated/onboarding.profile'
import { Route as AuthenticatedOnboardingNotificationsRouteImport } from './routes/_authenticated/onboarding.notifications'
import { Route as AuthenticatedOnboardingEfootballRouteImport } from './routes/_authenticated/onboarding.efootball'
import { Route as AuthenticatedOnboardingAvailabilityRouteImport } from './routes/_authenticated/onboarding.availability'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminPayoutsRouteImport } from './routes/_authenticated/admin/payouts'
import { Route as AuthenticatedAdminFlaggedMatchesRouteImport } from './routes/_authenticated/admin/flagged-matches'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuickcashRoute = AuthenticatedQuickcashRouteImport.update({
  id: '/quickcash',
  path: '/quickcash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeagueRoute = AuthenticatedLeagueRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardsRoute =
  AuthenticatedLeaderboardsRouteImport.update({
    id: '/leaderboards',
    path: '/leaderboards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTournamentsIndexRoute =
  AuthenticatedTournamentsIndexRouteImport.update({
    id: '/tournaments/',
    path: '/tournaments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTournamentsNewRoute =
  AuthenticatedTournamentsNewRouteImport.update({
    id: '/tournaments/new',
    path: '/tournaments/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTournamentsIdRoute =
  AuthenticatedTournamentsIdRouteImport.update({
    id: '/tournaments/$id',
    path: '/tournaments/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayerUserIdRoute =
  AuthenticatedPlayerUserIdRouteImport.update({
    id: '/player/$userId',
    path: '/player/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingProfileRoute =
  AuthenticatedOnboardingProfileRouteImport.update({
    id: '/onboarding/profile',
    path: '/onboarding/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingNotificationsRoute =
  AuthenticatedOnboardingNotificationsRouteImport.update({
    id: '/onboarding/notifications',
    path: '/onboarding/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingEfootballRoute =
  AuthenticatedOnboardingEfootballRouteImport.update({
    id: '/onboarding/efootball',
    path: '/onboarding/efootball',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingAvailabilityRoute =
  AuthenticatedOnboardingAvailabilityRouteImport.update({
    id: '/onboarding/availability',
    path: '/onboarding/availability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPayoutsRoute =
  AuthenticatedAdminPayoutsRouteImport.update({
    id: '/admin/payouts',
    path: '/admin/payouts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFlaggedMatchesRoute =
  AuthenticatedAdminFlaggedMatchesRouteImport.update({
    id: '/admin/flagged-matches',
    path: '/admin/flagged-matches',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/leaderboards': typeof AuthenticatedLeaderboardsRoute
  '/league': typeof AuthenticatedLeagueRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quickcash': typeof AuthenticatedQuickcashRoute
  '/admin/flagged-matches': typeof AuthenticatedAdminFlaggedMatchesRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/onboarding/availability': typeof AuthenticatedOnboardingAvailabilityRoute
  '/onboarding/efootball': typeof AuthenticatedOnboardingEfootballRoute
  '/onboarding/notifications': typeof AuthenticatedOnboardingNotificationsRoute
  '/onboarding/profile': typeof AuthenticatedOnboardingProfileRoute
  '/player/$userId': typeof AuthenticatedPlayerUserIdRoute
  '/tournaments/$id': typeof AuthenticatedTournamentsIdRoute
  '/tournaments/new': typeof AuthenticatedTournamentsNewRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/tournaments/': typeof AuthenticatedTournamentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/leaderboards': typeof AuthenticatedLeaderboardsRoute
  '/league': typeof AuthenticatedLeagueRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quickcash': typeof AuthenticatedQuickcashRoute
  '/admin/flagged-matches': typeof AuthenticatedAdminFlaggedMatchesRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/onboarding/availability': typeof AuthenticatedOnboardingAvailabilityRoute
  '/onboarding/efootball': typeof AuthenticatedOnboardingEfootballRoute
  '/onboarding/notifications': typeof AuthenticatedOnboardingNotificationsRoute
  '/onboarding/profile': typeof AuthenticatedOnboardingProfileRoute
  '/player/$userId': typeof AuthenticatedPlayerUserIdRoute
  '/tournaments/$id': typeof AuthenticatedTournamentsIdRoute
  '/tournaments/new': typeof AuthenticatedTournamentsNewRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/tournaments': typeof AuthenticatedTournamentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/leaderboards': typeof AuthenticatedLeaderboardsRoute
  '/_authenticated/league': typeof AuthenticatedLeagueRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/quickcash': typeof AuthenticatedQuickcashRoute
  '/_authenticated/admin/flagged-matches': typeof AuthenticatedAdminFlaggedMatchesRoute
  '/_authenticated/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/onboarding/availability': typeof AuthenticatedOnboardingAvailabilityRoute
  '/_authenticated/onboarding/efootball': typeof AuthenticatedOnboardingEfootballRoute
  '/_authenticated/onboarding/notifications': typeof AuthenticatedOnboardingNotificationsRoute
  '/_authenticated/onboarding/profile': typeof AuthenticatedOnboardingProfileRoute
  '/_authenticated/player/$userId': typeof AuthenticatedPlayerUserIdRoute
  '/_authenticated/tournaments/$id': typeof AuthenticatedTournamentsIdRoute
  '/_authenticated/tournaments/new': typeof AuthenticatedTournamentsNewRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/tournaments/': typeof AuthenticatedTournamentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/leaderboards'
    | '/league'
    | '/profile'
    | '/quickcash'
    | '/admin/flagged-matches'
    | '/admin/payouts'
    | '/admin/users'
    | '/onboarding/availability'
    | '/onboarding/efootball'
    | '/onboarding/notifications'
    | '/onboarding/profile'
    | '/player/$userId'
    | '/tournaments/$id'
    | '/tournaments/new'
    | '/admin/'
    | '/tournaments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/leaderboards'
    | '/league'
    | '/profile'
    | '/quickcash'
    | '/admin/flagged-matches'
    | '/admin/payouts'
    | '/admin/users'
    | '/onboarding/availability'
    | '/onboarding/efootball'
    | '/onboarding/notifications'
    | '/onboarding/profile'
    | '/player/$userId'
    | '/tournaments/$id'
    | '/tournaments/new'
    | '/admin'
    | '/tournaments'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/home'
    | '/_authenticated/leaderboards'
    | '/_authenticated/league'
    | '/_authenticated/profile'
    | '/_authenticated/quickcash'
    | '/_authenticated/admin/flagged-matches'
    | '/_authenticated/admin/payouts'
    | '/_authenticated/admin/users'
    | '/_authenticated/onboarding/availability'
    | '/_authenticated/onboarding/efootball'
    | '/_authenticated/onboarding/notifications'
    | '/_authenticated/onboarding/profile'
    | '/_authenticated/player/$userId'
    | '/_authenticated/tournaments/$id'
    | '/_authenticated/tournaments/new'
    | '/_authenticated/admin/'
    | '/_authenticated/tournaments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quickcash': {
      id: '/_authenticated/quickcash'
      path: '/quickcash'
      fullPath: '/quickcash'
      preLoaderRoute: typeof AuthenticatedQuickcashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/league': {
      id: '/_authenticated/league'
      path: '/league'
      fullPath: '/league'
      preLoaderRoute: typeof AuthenticatedLeagueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboards': {
      id: '/_authenticated/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof AuthenticatedLeaderboardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tournaments/': {
      id: '/_authenticated/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof AuthenticatedTournamentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tournaments/new': {
      id: '/_authenticated/tournaments/new'
      path: '/tournaments/new'
      fullPath: '/tournaments/new'
      preLoaderRoute: typeof AuthenticatedTournamentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tournaments/$id': {
      id: '/_authenticated/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof AuthenticatedTournamentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/player/$userId': {
      id: '/_authenticated/player/$userId'
      path: '/player/$userId'
      fullPath: '/player/$userId'
      preLoaderRoute: typeof AuthenticatedPlayerUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/profile': {
      id: '/_authenticated/onboarding/profile'
      path: '/onboarding/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof AuthenticatedOnboardingProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/notifications': {
      id: '/_authenticated/onboarding/notifications'
      path: '/onboarding/notifications'
      fullPath: '/onboarding/notifications'
      preLoaderRoute: typeof AuthenticatedOnboardingNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/efootball': {
      id: '/_authenticated/onboarding/efootball'
      path: '/onboarding/efootball'
      fullPath: '/onboarding/efootball'
      preLoaderRoute: typeof AuthenticatedOnboardingEfootballRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/availability': {
      id: '/_authenticated/onboarding/availability'
      path: '/onboarding/availability'
      fullPath: '/onboarding/availability'
      preLoaderRoute: typeof AuthenticatedOnboardingAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payouts': {
      id: '/_authenticated/admin/payouts'
      path: '/admin/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AuthenticatedAdminPayoutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/flagged-matches': {
      id: '/_authenticated/admin/flagged-matches'
      path: '/admin/flagged-matches'
      fullPath: '/admin/flagged-matches'
      preLoaderRoute: typeof AuthenticatedAdminFlaggedMatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLeaderboardsRoute: typeof AuthenticatedLeaderboardsRoute
  AuthenticatedLeagueRoute: typeof AuthenticatedLeagueRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQuickcashRoute: typeof AuthenticatedQuickcashRoute
  AuthenticatedAdminFlaggedMatchesRoute: typeof AuthenticatedAdminFlaggedMatchesRoute
  AuthenticatedAdminPayoutsRoute: typeof AuthenticatedAdminPayoutsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedOnboardingAvailabilityRoute: typeof AuthenticatedOnboardingAvailabilityRoute
  AuthenticatedOnboardingEfootballRoute: typeof AuthenticatedOnboardingEfootballRoute
  AuthenticatedOnboardingNotificationsRoute: typeof AuthenticatedOnboardingNotificationsRoute
  AuthenticatedOnboardingProfileRoute: typeof AuthenticatedOnboardingProfileRoute
  AuthenticatedPlayerUserIdRoute: typeof AuthenticatedPlayerUserIdRoute
  AuthenticatedTournamentsIdRoute: typeof AuthenticatedTournamentsIdRoute
  AuthenticatedTournamentsNewRoute: typeof AuthenticatedTournamentsNewRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedTournamentsIndexRoute: typeof AuthenticatedTournamentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLeaderboardsRoute: AuthenticatedLeaderboardsRoute,
  AuthenticatedLeagueRoute: AuthenticatedLeagueRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQuickcashRoute: AuthenticatedQuickcashRoute,
  AuthenticatedAdminFlaggedMatchesRoute: AuthenticatedAdminFlaggedMatchesRoute,
  AuthenticatedAdminPayoutsRoute: AuthenticatedAdminPayoutsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedOnboardingAvailabilityRoute:
    AuthenticatedOnboardingAvailabilityRoute,
  AuthenticatedOnboardingEfootballRoute: AuthenticatedOnboardingEfootballRoute,
  AuthenticatedOnboardingNotificationsRoute:
    AuthenticatedOnboardingNotificationsRoute,
  AuthenticatedOnboardingProfileRoute: AuthenticatedOnboardingProfileRoute,
  AuthenticatedPlayerUserIdRoute: AuthenticatedPlayerUserIdRoute,
  AuthenticatedTournamentsIdRoute: AuthenticatedTournamentsIdRoute,
  AuthenticatedTournamentsNewRoute: AuthenticatedTournamentsNewRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedTournamentsIndexRoute: AuthenticatedTournamentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
